[development]
address = "127.0.0.1"
port = 8080
keep_alive = 5
log = "debug"
limits = { forms = 32768 }

[production]
address = "127.0.0.1"
port = 8080
keep_alive = 5
log = "debug"
limits = { forms = 32768 }