# infrastructure/Cargo.toml

[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"


[dependencies]
diesel = { version = "2.0.0", features = ["postgres", "uuid"] }
uuid = { version = "1.3.3", features = ["v4"] }

dotenvy = "0.15"
